### ISSUE TITLE
Offset anchors so the navbar doesn't cover them

### ISSUE THREAD

**Issue by TomAugspurger** [dask/dask-sphinx-theme#11]
If you navigate to the anchor at http://ml.dask.org/modules/generated/dask_ml.wrappers.Incremental.html#dask_ml.wrappers.Incremental, the section title the anchor is attached to is covered by the navbar. @dsludwig do you know, is there a way to "offset" the anchors so that navigating to them places them below the navbar on your screen?

**Comment by jrbourbeau** [comment]
Closed by #27
