### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask-sphinx-theme#13]
I'd like to have a new release of `dask-sphinx-theme` which includes the changes from #12. Are others okay with this? @mrocklin if you want to add me on PyPI (jrbourbeau) I'd be happy to handle the release

**Comment by mrocklin** [comment]
Done.  You now have ownership rights

**Comment by jrbourbeau** [comment]
Thanks @mrocklin! Closing this issue as v1.1.1 is live on PyPI
