### ISSUE TITLE
Automate releases

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/dask-sphinx-theme#25]
_This was discussed at the weekly developers meeting._

This repo is changed infrequently, and it is highly likely that a release will be required immediately after any change.

Therefore I would be keen to automate this via some CI/CD (Travis, Circle, Pipelines, etc).

**Comment by mrocklin** [comment]
+1 from me

**Comment by jrbourbeau** [comment]
That sounds great to me

**Comment by jsignell** [comment]
Should this be closed? It looks like there is an action that releases to pypi when a tag is pushed, but I don't see any documentation about that.
