### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by TomAugspurger** [dask/dask-sphinx-theme#33]

**Comment by jacobtomlinson** [comment]
`1.3.1` tag pushed.

🤞🏻 for the GitHub Action.

**Comment by jrbourbeau** [comment]
So it looks like the action only runs on pushes to `master`. I bumped the `__version__` to 1.3.1 and added a tag in d52225a25b1d8742f1d71343f8a65138d9710430, but the action still didn't run the package building and publishing steps. 

@jacobtomlinson do you think this condition

https://github.com/dask/dask-sphinx-theme/blob/d52225a25b1d8742f1d71343f8a65138d9710430/.github/workflows/publish-pypi.yml#L26

is off?

**Comment by jacobtomlinson** [comment]
I think the condition is fine, but the workflow isn't being triggered on tags, only pushes to master.

I've raised #34 to resolve this.

**Comment by jrbourbeau** [comment]
Closing as 1.3.1 is on PyPI and conda-forge. Thanks @jacobtomlinson!
