### ISSUE TITLE
FYI: CSS fixes in nbsphinx

### ISSUE THREAD

**Issue by mgeier** [dask/dask-sphinx-theme#36]
This isn't actually an issue (at least I hope not), I just wanted to give y'all a heads up:

I'm planning to add some CSS fixes to `nbsphinx` when the dask theme is used: https://github.com/spatialaudio/nbsphinx/pull/415

I think some of those fixes are already included in the dask theme, but my change hopefully doesn't hurt them.

If you have concerns, suggestions for improvements or any other comments, please let me know!

**Comment by mrocklin** [comment]
Thank you for maintaining nbsphinx @mgeier , and for giving us special consideration.  Is there anything that we should know about these changes or do here?

**Comment by mgeier** [comment]
It would be great if you could have a look at the additional CSS to see if it looks reasonable to you.

I think the main visible change is that after the change there will be more space after code cells and before the following paragraph of text.

**Comment by mrocklin** [comment]
I would be happy to take a look, but I'll admit that my experience with CSS is not great, so I may not be able to quickly determine what is going on.  In general I'm inclined to trust your judgment here.

**Comment by mgeier** [comment]
I don't think this change is problematic, but it would not hurt if you just had a quick look at the CSS to see if anything looks fishy to you.

https://github.com/spatialaudio/nbsphinx/blob/5b70fd1732e604857eac9b742d76a1bbd4d6416a/src/nbsphinx.py#L634-L656

**Comment by mrocklin** [comment]
Nothing looks fishy to me, but that's mostly because I don't understand
most of it :)

**Comment by mgeier** [comment]
OK, thanks for looking!

I've just merged the PR.

After the next release we will see whether there are any complaints.

If there are, please let me know.

BTW, this is how the `nbsphinx` docs look with the dask theme: https://nbsphinx.readthedocs.io/en/dask-theme/

**Comment by mrocklin** [comment]
Oh interesting.  Are you aware of https://examples.dask.org/array.html ?

**Comment by mrocklin** [comment]
We use nbsphinx extensively there

**Comment by mgeier** [comment]
I've heard about it, but I haven't used it myself. Cool stuff!
