### ISSUE TITLE
Add Dask Gateway to "Setup"

### ISSUE THREAD

**Issue by TomAugspurger** [dask/dask-sphinx-theme#37]
Dask-Gateway should be in https://github.com/dask/dask-sphinx-theme/blob/012a141550ce2dc4ba96e2c7f3b8743ab4668701/dask_sphinx_theme/layout.html#L153-L160

What one or two word phrase should we use @jcrist? "Managed"?

I also want to add it to the doc page at https://docs.dask.org/en/latest/setup.html.

**Comment by jsignell** [comment]
This whole section is getting removed, so I'm going to close this issue.
