### ISSUE TITLE
Theme fails to style api docs with `sphinx-rtd-theme==0.5.0`

### ISSUE THREAD

**Issue by jcrist** [dask/dask-sphinx-theme#44]
The latest version of `sphinx-rtd-theme` (which `dask-sphinx-theme` is built on) is 0.5.0. With that installed, api docs fail to style properly.

**With `sphinx-rtd-theme==0.5.0`**

<img width="748" alt="Screen Shot 2020-10-02 at 5 14 36 PM" src="https://user-images.githubusercontent.com/2783717/94974058-06957200-04d3-11eb-88a4-9f6bf32ca67e.png">

**With `sphinx-rtd-theme==0.4.3`**

<img width="732" alt="Screen Shot 2020-10-02 at 5 14 25 PM" src="https://user-images.githubusercontent.com/2783717/94974056-04cbae80-04d3-11eb-8491-3d218f12aea4.png">

When using `sphinx-rtd-theme==0.5.0` instead of `dask-sphinx-theme` things work properly, so it's something about the dask theme itself that breaks things. For now I'm pinning to 0.4.3 in dask-gateway to workaround the issue.

**Comment by mrocklin** [comment]
cc @gforsyth :)

**Comment by gforsyth** [comment]
I think I might've fixed this already?  @jcrist was this with `dask-sphinx-theme==1.3.3`?

On my machine with:

```
$ conda list | grep sphinx                                                                                            
dask-sphinx-theme         1.3.3                    pypi_0    pypi
sphinx                    3.2.1                      py_0    conda-forge
sphinx-rtd-theme          0.5.0                    pypi_0    pypi
```

and building `dask-gateway` docs from current master I see:

![2020-10-03-104636_736x593_scrot](https://user-images.githubusercontent.com/3596999/94994582-799bf880-0566-11eb-845f-e8328f657d10.png)
