### ISSUE TITLE
Favicon no longer appearing

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask-sphinx-theme#45]
Previously there was a tiny Dask logo for documentation pages using this theme. Today I noticed this is no longer the case:

<img width="363" alt="Screen Shot 2020-10-05 at 9 28 59 AM" src="https://user-images.githubusercontent.com/11656932/95092561-66fffb80-06ed-11eb-932b-519b5c15c67d.png">

**Comment by mrocklin** [comment]
@gforsyth

**Comment by gforsyth** [comment]
Whoops.  Yeah, that was probably me.  I'll take a look.

**Comment by jrbourbeau** [comment]
Just a heads up, I'm about to open a PR adding it back in
