### ISSUE TITLE
Odd symbols coming up

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-sphinx-theme#47]
Note the text Dask in the upper left, as well as the quotes around "Big Data" (although did someone else already report this?)
![image](https://user-images.githubusercontent.com/306380/95119843-7a1cc680-0701-11eb-9e53-0a575f4bff7e.png)

**Comment by jrbourbeau** [comment]
Hmm that's unfortunate, thanks for reporting @mrocklin...I'm not sure what's causing this yet. Also cc @gforsyth for visibility 

> although did someone else already report this?

@jsignell reported this over in https://github.com/dask/dask/issues/6704. From what I can tell this issue doesn't appear on Firefox but does on Chrome (at least those are the two browsers I've tested on)

**Comment by gforsyth** [comment]
Sorry for the trouble.  I think this is (somehow) related to "smartquotes".

Annoyingly I can't get the symbols to show up locally (although I can see them on dask.org using Chrome or other chromium-based browsers).

A possible quick fix is to try disabling smartquotes altogether and see if it also fixes the weird rendering issue by the little "home" icon that's currently showing up as i-umlaut euro-cent

**Comment by jrbourbeau** [comment]
With @gforsyth's PR https://github.com/dask/dask-sphinx-theme/pull/48 the symbols associated with double-quotes are fixed

<img width="1552" alt="Screen Shot 2020-10-05 at 5 14 44 PM" src="https://user-images.githubusercontent.com/11656932/95137796-7ce1e080-072e-11eb-97b7-16ada279efd2.png">

But we're still getting a weird symbol next to "Dask" above the search bar (it should be a little house). But hey, progress!

**Comment by gforsyth** [comment]
And all of a sudden it's fixed...?

**Comment by jrbourbeau** [comment]
Closing as this seems to have fixed itself 🎉
