### ISSUE TITLE
Double scrollbar and footer issues

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask-sphinx-theme#74]
> Copied this over from @TomAugspurger's original comment here https://github.com/dask/community/issues/220#issuecomment-1147721844

Question about the new dask-sphinx-theme. On https://ml.dask.org/ I get a double vertical scrollbar:

<img width="1281" alt="image" src="https://user-images.githubusercontent.com/1312546/172217360-00f68d85-09d3-4913-9685-851017dd8848.png">

And I'm not sure if it's related, but the footer is cutoff halfway:

<img width="1152" alt="image" src="https://user-images.githubusercontent.com/1312546/172217461-d47789bf-2ab9-41ce-84c1-6a4fe144bfdc.png">

**Comment by jrbourbeau** [comment]
cc @scharlottej13 @jacobtomlinson in case you have some bandwidth to look at this

**Comment by scharlottej13** [comment]
Thx for creating the issue @jrbourbeau! I can take a look this week.

**Comment by jacobtomlinson** [comment]
I have bandwidth to review but not investigate directly so thanks for taking this on @scharlottej13.

**Comment by jsignell** [comment]
Closed by #75
