### ISSUE TITLE
Release 3.0.4

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask-sphinx-theme#82]
When building the `distributed` docs today I noticed there was a warning emitted that has been resolved on `main` by https://github.com/dask/dask-sphinx-theme/pull/80. I'd like to push out a new theme release with that update included. Will plan to do so next Tuesday if there are no blockers raised. 

cc @jacobtomlinson for visibility

**Comment by jacobtomlinson** [comment]
Sounds good thanks @jrbourbeau

**Comment by jrbourbeau** [comment]
Closing as 3.0.4 is on PyPI and conda-forge (xref https://github.com/conda-forge/dask-sphinx-theme-feedstock/pull/26)

**Comment by jacobtomlinson** [comment]
Thanks for handling this @jrbourbeau
